oruga-ui/theme-oruga

package-lock.json
package.json

Change version to 0.8.1 instead of file:../oruga/packages/oruga-next 
Fixes #7

chore: oruga version 0.8.1

---

src/assets/scss/components/_taginput.scss

fix(taginput): autocomplete position

---

src/assets/scss/components/_datepicker.scss

fix(datepicker): add cursor pointer when selectable

---

src/assets/scss/components/_select.scss
src/components/Select.vue

feat: add select-arrow-color var

---

src/assets/scss/components/_checkbox.scss
src/assets/scss/components/_radio.scss

Fixes #2
- Use mask-image for radio svgs

feat(radio): use mask for radio button svgs

---

src/assets/scss/components/_datepicker.scss

fix(datepicker): override dropdown item style with datepicker box variables

---

src/assets/scss/utils/_root.scss
src/assets/scss/utils/_variables.scss

- https://github.com/oruga-ui/theme-oruga/issues/32

feat:  allow the use of `:host` in variable definitions

---

src/assets/scss/components/_collapse.scss

fix(collapse): adjust trigger styling

---

src/assets/scss/components/_datetimepicker.scss

fix(datetimepicker): remove duplicate shadow

---

src/assets/scss/components/_select.scss

fix(select): remove `cursor: pointer` while `disabled`

---

src/components.ts
src/main.ts

docs: update example large icon size

---

src/assets/scss/components/_button.scss
src/assets/scss/components/_checkbox.scss
src/assets/scss/components/_input.scss
src/assets/scss/components/_radio.scss
src/assets/scss/components/_select.scss
src/assets/scss/components/_slider.scss
src/assets/scss/components/_switch.scss
src/assets/scss/components/_tabs.scss
src/assets/scss/components/_taginput.scss
src/assets/scss/utils/_helpers.scss
src/assets/scss/utils/_root.scss

feat: add focus styling

---

src/assets/scss/components/_select.scss

fix(select): fix expanded class

---

src/assets/scss/components/_autocomplete.scss

fix(autocomplete): add ` o-acp__item--hover` styling

---

src/assets/scss/components/_datepicker.scss
src/assets/scss/components/_select.scss

fix(datepicker): adjust expanded styling

---

src/assets/scss/components/_taginput.scss

fix(taginput): adjust expanded styling

---

src/assets/scss/components/_dropdown.scss

fix(dropdown): adjust z-index values

---

src/assets/scss/components/_menu.scss

feat(menu): enhance styling

---

src/assets/scss/components/_table.scss

fix(table): adjust column overlapped sticky header

---

src/assets/scss/components/_slider.scss

fix(slider): fix `border-radius` issue

---

src/assets/scss/components/_datepicker.scss

fix(datepicker): fix selection background color

---

src/assets/scss/components/_checkbox.scss

feat(checkbox): add checkbox `width` & `height` for different sizes

---

src/assets/scss/components/_dropdown.scss

- https://github.com/oruga-ui/theme-oruga/issues/70

fix: dropdown position it is not correct when set to "bottom-right"

---

src/assets/scss/components/_button.scss
src/main.ts

feat(button): add icon spacer

---

src/assets/scss/utils/_base.scss

feat(scroll): update `scrollClipClass` and  `scrollKeepClass`
